import pandas as pd
from pathlib import Path


def identify_and_drop_unusable_cols(frame: pd.DataFrame) -> pd.DataFrame:
    df = frame
    droppable_cols = []
    length = len(df)
    for col in df.columns:
        if (df[col].count() / length) <= 0.05 or df[col].nunique() < 2:
            droppable_cols.append(col)

    # print(f"dropping {len(droppable_cols)} cols")
    # [print(x) for x in sorted(droppable_cols)]
    return df.drop(columns=droppable_cols)


droppable_cols = [
    "Collimator Type",
    "Actual Frame Duration",
    "Position Reference Indicator",
    "Corrected Image",
    "Number of Slices",
    "Number of Time Slices",
    "Series Type",
    "Units",
    "Counts Source",
    "Decay Correction",
    "Frame Reference Time",
    "Image Index",
    "[Product id]",
    "[Table delta]",
    "[Cardiac repetition time]",
    "[Images per cardiac cycle]",
    "[Delay after trigger]",
    "[Pause Interval]",
    "[Pause Time]",
    "[Slice offset on freq axis]",
    "[Surface Coil Type]",
    "[Extremity Coil flag]",
    "[Calibrated Field strength]",
    "[User data 9]",
    "[User data 10]",
    "[User data 13]",
    "[User data 14]",
    "[User data 16]",
    "[User data 19]",
    "[Projection angle]",
    "[Phase Contrast flow axis]",
    "[Velocity encoding]",
    "[Thickness disclaimer]",
    "[Projection Algorithm]",
    "[Projection Algorithm Name]",
    "[Cardiac phase number]",
    "[Concatenated SAT {# DTI Diffusion Dir., release 9.0 & below}]",
    "[Velocity Encode Scale]",
    "[Fast phases]",
    "Laterality",
    "Stack ID",
    "[Rotation from source x rot]",
    "[Rotation from source y rot]",
    "[Rotation from source z rot]",
    "[Image Filtering 0.5/0.2T]",
    "[RTIA_timer]",
    "[Fps]",
    "[Auto window/level alpha]",
    "[Auto window/level beta]",
    "[Auto window/level window]",
    "[Auto window/level level]",
    "[Start time(secs) in first axial]",
    "[Indicates study has complete info (DICOM/genesis)]",
    "[Landmark Counter]",
    "[Series Complete Flag]",
    "[Number of images archived]",
    "[Image archive flag]",
    "[Scout Type]",
    "[Foreign Image Revision]",
    "[Lower range of Pixels1]",
    "[Upper range of Pixels1]",
    "[Lower range of Pixels2]",
    "[Upper range of Pixels2]",
    "[Version of the hdr struct]",
    "[Views per segment]",
    "[Respiratory rate, bpm]",
    "[Respiratory trigger point]",
    "[GE image integrity]",
    "[Filter Mode (String slop field 1 in legacy GE MR]",
    "[String slop field 2]",
    "[Image Type (real, imaginary, phase, magnitude)]",
    "[Neg_scanspacing]",
    "[User_fill_map_MSW]",
    "[User_fill_map_LSW]",
    "[Coil ID Data]",
    "[Prescan Reuse String]",
    "[ASSET Acquisition Calibration Series UID]",
    "[Rx Stack Identification]",
    "Pixel Padding Value",
    "Group Length",
    "[NEW/SEEN Status]",
    "[Receive Origin]",
    "[Receive Date]",
    "[Receive Time]",
    "[Receive Origin Description]",
    "[Full fidelity]",
    "Temporal Resolution",
    "[Series from which Prescribed]",
    "[PURE Acquisition Calibration Series UID]",
    "Date of Last Calibration",
    "Time of Last Calibration",
    "[CSA Series Header Type]",
    "[PMTF Information 1]",
    "[PMTF Information 2]",
    "[PMTF Information 3]",
    "[PMTF Information 4]",
    "[Series Workflow Status]",
    "Synchronization Frame of Reference UID",
    "Concatenation UID",
    "[CSA Image Header Version ??]",
    "[PositivePCSDirections]",
    "Study Status ID",
    "[Mitra Rotation]",
    "[Mitra Window Width]",
    "[Mitra Window Centre]",
    "[Mitra Invert]",
    "Derivation Description",
    "Requesting Service",
    "Length to End",
    "Nominal Interval",
    "[FMRIStimulInfo]",
    "Code Value",
    "Coding Scheme Designator",
    "Intervals Acquired",
    "Intervals Rejected",
    "Study Arrival Date",
    "Study Arrival Time",
    "Study Completion Date",
    "Study Completion Time",
    "[Chemical Shift]",
    "[Chemical Shift Number MR]",
    "[Diffusion B-Factor]",
    "[Diffusion Direction]",
    "[Image Enhanced]",
    "[Image Type ED ES]",
    "[Phase Number]",
    "[Slice Number MR]",
    "[Slice Orientation]",
    "[Cardiac Sync]",
    "[Diffusion Echo Time]",
    "[Dynamic Series]",
    "[EPI Factor]",
    "[Number of Echoes]",
    "[Number of Locations]",
    "[Number of PC Directions]",
    "[Number of Phases MR]",
    "[Number of Slices MR]",
    "[Partial Matrix Scanned]",
    "[PC Velocity]",
    "[Prepulse Delay]",
    "[Prepulse Type]",
    "[Reconstruction Number MR]",
    "[Respiration Sync]",
    "[Scanning Technique Description MR]",
    "[SPIR]",
    "[Water Fat Shift]",
    "[Flip Angle Philips]",
    "[Interactive]",
    "[Echo Time Display MR]",
    "[Number of Stacks]",
    "[Examination Source]",
    "[Acquisition Number]",
    "[Number of Dynamic Scans]",
    "[Echo Train Length]",
    "[Imaging Frequency]",
    "[Inversion Time]",
    "[Magnetic Field Strength]",
    "[Imaged Nucleus]",
    "[Number of Averages]",
    "[Phase FOV Percent]",
    "[Sampling Percent]",
    "[Prospective Motion Correction]",
    "[Window Center]",
    "[Window Width]",
    "[Number of Chemical Shift]",
    "[Repetition Time]",
    "[Syncra Scan Type]",
    "[Diffusion Direction RL]",
    "[Diffusion Direction AP]",
    "[Diffusion Direction FH]",
    "Presentation LUT Shape",
    "Frame Type",
    "Creator-Version UID",
    "Pixel Presentation",
    "Volumetric Properties",
    "Volume Based Calculation Technique",
    "Complex Image Component",
    "Acquisition Contrast",
    "Contrast/Bolus Volume",
    "Contrast/Bolus Ingredient Concentration",
    "Pulse Sequence Name",
    "Echo Pulse Sequence",
    "Inversion Recovery",
    "Multiple Spin Echo",
    "Multi-planar Excitation",
    "Phase Contrast",
    "Time of Flight Contrast",
    "Spoiling",
    "Steady State Pulse Sequence",
    "Echo Planar Pulse Sequence",
    "Magnetization Transfer",
    "T2 Preparation",
    "Blood Signal Nulling",
    "Saturation Recovery",
    "Spectrally Selected Suppression",
    "Spectrally Selected Excitation",
    "Spatial Pre-saturation",
    "Tagging",
    "Oversampling Phase",
    "Geometry of k-Space Traversal",
    "Segmented k-Space Traversal",
    "Rectilinear Phase Encode Reordering",
    "Tag Thickness",
    "Partial Fourier Direction",
    "Cardiac Synchronization Technique",
    "Receive Coil Manufacturer Name",
    "Receive Coil Type",
    "Quadrature Receive Coil",
    "Multi-Coil Element Name",
    "Multi-Coil Element Used",
    "Transmit Coil Type",
    "Chemical Shift Reference",
    "MR Acquisition Frequency Encoding Steps",
    "De-coupling",
    "k-space Filtering",
    "Parallel Reduction Factor In-plane",
    "Diffusion Directionality",
    "Parallel Acquisition",
    "Parallel Acquisition Technique",
    "Inversion Times",
    "Metabolite Map Description",
    "Partial Fourier",
    "Velocity Encoding Direction",
    "Velocity Encoding Minimum Value",
    "Number of k-Space Trajectories",
    "Frequency Correction",
    "Diffusion Anisotropy Type",
    "Parallel Reduction Factor out-of-plane",
    "Parallel Reduction Factor Second In-plane",
    "Respiratory Motion Compensation Technique",
    "Respiratory Signal Source",
    "Bulk Motion Compensation Technique",
    "Applicable Safety Standard Agency",
    "Specific Absorption Rate Definition",
    "Gradient Output Type",
    "Specific Absorption Rate Value",
    "Gradient Output",
    "Water Referenced Phase Correction",
    "MR Spectroscopy Acquisition Type",
    "MR Acquisition Phase Encoding Steps in-plane",
    "MR Acquisition Phase Encoding Steps out-of-plane",
    "RF Echo Train Length",
    "Gradient Echo Train Length",
    "Frame Laterality",
    "Respiratory Interval Time",
    "Nominal Respiratory Trigger Delay Time",
    "LUT Explanation",
    "Data Point Rows",
    "Data Point Columns",
    "LUT Label",
    "Coverage of k-Space",
    "Flow Compensation Direction",
    "Conversion Type",
    "Patient Orientation",
    "Planar Configuration",
    "Retrieve AE Title",
    "Study Priority ID",
    "Data Set Type",
    "Data Set Subtype",
    "[Unique Identifier]",
    "[Organ]",
    "[Patient Name]",
    "[Key Images]",
    "[Image Number]",
    "[Tamar Study Body Part]",
    "[Tamar Site Id]",
    "[Tamar Translate Flags]",
    "[Tamar Exe Software Version]",
    "[Tamar Study Has Sticky Note]",
    "Date of Secondary Capture",
    "Time of Secondary Capture",
    "Confidentiality Code",
    "Contrast/Bolus Total Dose",
    "Contrast/Bolus Ingredient",
    "Filler Order Number / Imaging Service Request",
    "Image Position",
    "Image Orientation",
    "Location",
    "Image Geometry Type",
    "Masking Image",
    "Acquisitions in Series",
    "Image Dimensions",
    "Image Format",
    "Image Location",
    "Patient's Birth Name",
    "Patient's Mother's Birth Name",
    "Country of Residence",
    "Smoking Status",
    "Patient's Religious Preference",
    "[number of images in series]",
    "[Tamar Study Status]",
    "[Tamar Study Age]",
    "[Institution Code]",
    "[Source AE]",
    "[Deferred Validation]",
    "[Series Owner]",
    "Pixel Aspect Ratio",
    "Requested Contrast Agent",
    "Performed Procedure Step Status",
    "Performed Procedure Type Description",
    "Requested Procedure ID",
    "Requested Procedure Priority",
    "Requested Procedure Location",
    "Names of Intended Recipients of Results",
    "Requested Procedure Comments",
    "Placer Order Number / Imaging Service Request (Retired)",
    "Filler Order Number / Imaging Service Request (Retired)",
    "Order Entered By",
    "[Series Type]",
    "Special Needs",
    "[Tamar Compression Type]",
    "[MedCom OOG Type]",
    "[MedCom OOG Version]",
    "Overlay Rows",
    "Overlay Columns",
    "Number of Frames in Overlay",
    "Overlay Description",
    "Overlay Type",
    "Overlay Origin",
    "Image Frame Origin",
    "Overlay Bits Allocated",
    "Overlay Bit Position",
    "Convolution Kernel",
    "Randoms Correction Method",
    "Scatter Correction Method",
    "Decay Factor",
    "Number of Frames",
    "Red Palette Color Lookup Table Descriptor",
    "Green Palette Color Lookup Table Descriptor",
    "Blue Palette Color Lookup Table Descriptor",
    "[Reject Image Flag]",
    "[Significant Flag]",
    "[Confidential Flag]",
    "[Assigning Authority For Patient ID]",
    "[GE IIS Compression ID]",
    "[Original Study Instance UID]",
    "[Patient's Name]",
    "[Study Description]",
    "[Referring Physician's Name]",
    "[Requesting Physician's Name]",
    "[Reason for Study]",
    "[Study Comments]",
    "[Performing Physician's Name]",
    "Smallest Pixel Value in Series",
    "Largest Pixel Value in Series",
    "Contrast/Bolus Route",
    "Acquisition DateTime",
    "Beat Rejection Flag",
    "Content Qualification",
    "Burned In Annotation",
    "Secondary Capture Device ID",
    "Secondary Capture Device Manufacturer",
    "Secondary Capture Device Manufacturer's Model Name",
    "Secondary Capture Device Software Versions",
    "Digital Image Format Acquired",
    "B1rms",
    "Relative Opacity",
    "Last Menstrual Date",
    "Temporal Position Index",
    "Lossy Image Compression Ratio",
    "Lossy Image Compression Method",
    "Scheduled Study Start Date",
    "Scheduled Study Start Time",
    "Query/Retrieve Level",
    "Instance Availability",
    "Skip Beats",
    "[Breast Box x0]",
    "Tag Angle First Axis",
    "Tag Spacing First Dimension",
    "Transmit Coil Manufacturer Name",
    "De-coupled Nucleus",
    "De-coupling Method",
    "Time Domain Filtering",
    "Cardiac Signal Source",
    "Cardiac Beat Rejection Technique",
    "Diffusion b-value XX",
    "Diffusion b-value XY",
    "Diffusion b-value XZ",
    "Diffusion b-value YY",
    "Diffusion b-value YZ",
    "Diffusion b-value ZZ",
    "Respiratory Trigger Delay Threshold",
    "Signal Domain Columns",
    "Data Representation",
    "Resonant Nucleus",
    "Referring Physician's Telephone Numbers",
    "Study Read Date",
    "Study Read Time",
    "[Private Creator]",
    "Number of Series Related Instances",
    "[Original Series Instance UID]",
    "[Original SOP Instance UID]",
    "Storage Media File-set UID",
    "[Breast Box y0]",
    "[Breast Box x1]",
    "[Breast Box y1]",
    "Issuer of Patient ID",
    "[Stentor Remote AETitle Element]",
    "[Stentor Local AETitle Element]",
    "[Stentor Transfer Syntax Value]",
    "[Patient's Name Single Byte]",
    "[Requesting Physician's Name Single Byte]",
    "[Window Smoothing Taste]",
    "[GL TrafoType]",
    "[Retrospective Motion Correction]",
    "[Functional Proc Group Name]",
    "[Functional Processing Name]",
    "[Bias of Functional Image]",
    "[Scale of Functional Image]",
    "[Length of Parameters String]",
    "[Store Parameters string, delimited by character ESC=0x1B (27)]",
    "[Functional Image Version]",
    "[Store Color Ramp]",
    "[Store Width of Functional Image]",
    "[Store level of Functional Image]",
    "[Analysis Package]",
    "[Original Study UID]",
    "[NPW factor]",
    "[Referring Physician's Name Single Byte]",
    "Patient's Birth Time",
    "Palette Color Lookup Table UID",
]


def combine_directory_excel_files(directory: str, output_file: str):
    combined_frame = pd.DataFrame()
    for file in Path(directory).glob("*.xlsx"):
        print(file)
        current_frame = pd.read_excel(file)
        current_frame = current_frame.drop(columns=droppable_cols)
        combined_frame = pd.concat([combined_frame, current_frame])

    print("Excel Files Read")

    combined_frame.to_excel(output_file, sheet_name="results", engine="openpyxl")


if __name__ == "__main__":
    excel_files_directory: str = ""
    output_file: str = ""
    combine_directory_excel_files(excel_files_directory, output_file)
