name: Pull Request to Main
on:
  pull_request:
    branches:
      - "main"
jobs:
  pr_to_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true  # Ensure LFS files are checked out

      - name: Install Git LFS
        run: |
          git lfs install
          git lfs pull

      - name: Set up Python 3.10.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

      - name: Run tests
        working-directory: ./tests
        run: pytest
